# Unit 12 - Tales from the Crypto

---

## 1. Sentiment Analysis

Use the [newsapi](https://newsapi.org/) to pull the latest news articles for Bitcoin and Ethereum and create a DataFrame of sentiment scores for each coin.

Use descriptive statistics to answer the following questions:
1. Which coin had the highest mean positive score?
2. Which coin had the highest negative score?
3. Which coin had the highest positive score?

In [1]:
# Initial imports
import os
import pandas as pd
from dotenv import load_dotenv
load_dotenv()
import nltk as nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

%matplotlib inline

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/jcmignon/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [2]:
# Read your api key environment variable
api_key = os.getenv("NEWS_API_KEY")

In [3]:
# Create a newsapi client
from newsapi import NewsApiClient
newsapi = NewsApiClient(api_key=api_key)

In [36]:
# Fetch the Bitcoin news articles
btc_news1 = pd.DataFrame(newsapi.get_everything(q="bitcoin", language ="en",sort_by='relevancy',page = 1)['articles'])
btc_news2 = pd.DataFrame(newsapi.get_everything(q="bitcoin", language ="en",sort_by='relevancy',page = 2)['articles'])
btc_news3 = pd.DataFrame(newsapi.get_everything(q="bitcoin", language ="en",sort_by='relevancy',page = 3)['articles'])
btc_news4 = pd.DataFrame(newsapi.get_everything(q="bitcoin", language ="en",sort_by='relevancy',page = 4)['articles'])
btc_news5 = pd.DataFrame(newsapi.get_everything(q="bitcoin", language ="en",sort_by='relevancy',page = 5)['articles'])

btc_news = pd.concat([btc_news1,btc_news2,btc_news3,btc_news4,btc_news5])
btc_news

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': 'engadget', 'name': 'Engadget'}",https://www.engadget.com/about/editors/saqib-shah,El Salvador becomes the first country to appro...,El Salvador has voted to adopt Bitcoin as lega...,https://www.engadget.com/el-salvador-bitcoin-l...,https://s.yimg.com/os/creatr-uploaded-images/2...,2021-06-09T12:04:40Z,El Salvador's President Nayib Bukele has made ...
1,"{'id': None, 'name': 'Gizmodo.com'}",Matt Novak,El Salvador Becomes First Country to Recognize...,El Salvador has become the first country in th...,https://gizmodo.com/el-salvador-becomes-first-...,https://i.kinja-img.com/gawker-media/image/upl...,2021-06-09T10:00:00Z,El Salvador has become the first country in th...
2,"{'id': 'mashable', 'name': 'Mashable'}",Stan Schroeder,Elon Musk says Tesla will resume Bitcoin purch...,"It's all about clean energy, it seems. \nElon ...",https://mashable.com/article/tesla-bitcoin-pur...,https://mondrian.mashable.com/2021%252F06%252F...,2021-06-14T07:15:49Z,"It's all about clean energy, it seems. \r\nElo..."
3,"{'id': 'bbc-news', 'name': 'BBC News'}",https://www.facebook.com/bbcnews,Bitcoin: El Salvador makes cryptocurrency lega...,It is the first country in the world to make t...,https://www.bbc.co.uk/news/world-latin-america...,https://ichef.bbci.co.uk/news/1024/branded_new...,2021-06-09T08:27:58Z,image captionThe move means bitcoin will be ac...
4,"{'id': None, 'name': 'Gizmodo.com'}",Alyse Stanley,Miami's Bitcoin Conference May Be the Latest C...,"Several crypto fans that descended on Miami, F...",https://gizmodo.com/miamis-bitcoin-conference-...,https://i.kinja-img.com/gawker-media/image/upl...,2021-06-11T00:45:00Z,"Several crypto fans that descended on Miami, F..."
...,...,...,...,...,...,...,...,...
15,"{'id': 'reuters', 'name': 'Reuters'}",Reuters,Sotheby's diamond auction marks another bitcoi...,A rare pear-shaped diamond that is expected to...,https://www.reuters.com/technology/sothebys-di...,https://www.reuters.com/resizer/WRdJ_6_WGCwTd1...,2021-06-21T15:16:00Z,"A logo is pictured on Sotheby's in Geneva, Swi..."
16,"{'id': 'reuters', 'name': 'Reuters'}",Huw Jones,Bank regulators plan 'conservative' capital ru...,Banks must set aside enough capital to cover l...,https://www.reuters.com/business/bank-regulato...,https://www.reuters.com/resizer/nEtevxF8w62kQ6...,2021-06-10T10:08:00Z,Banks must set aside enough capital to cover l...
17,"{'id': 'reuters', 'name': 'Reuters'}",Iain Withers,Dollar holds gains after Fed boost; bitcoin tu...,The dollar held on to the previous week's gain...,https://www.reuters.com/business/dollar-holds-...,https://www.reuters.com/resizer/Wqc98RwaqtfoKV...,2021-06-21T08:26:00Z,"LONDON, June 21 (Reuters) - The dollar held on..."
18,"{'id': 'reuters', 'name': 'Reuters'}",Reuters,Square to invest $5 mln in Blockstream's solar...,Blockchain technology company Blockstream Mini...,https://www.reuters.com/technology/square-inve...,None,2021-06-05T18:22:00Z,Blockchain technology company Blockstream Mini...
19,"{'id': 'reuters', 'name': 'Reuters'}",Tom Wilson,"EXCLUSIVE El Salvador bitcoin transfers soar, ...",Small transfers of bitcoin to El Salvador jump...,https://www.reuters.com/business/finance/exclu...,https://www.reuters.com/resizer/AUSGmfvZnVBr2N...,2021-06-14T14:24:00Z,: Bitcoin banners are seen outside of a small ...

In [16]:
# Fetch the Ethereum news articles
eth_news = newsapi.get_everything(q="ethereum", language ="en",sort_by='relevancy')

eth_news1 = pd.DataFrame(newsapi.get_everything(q="ethereum", language ="en",sort_by='relevancy',page = 1)['articles'])
eth_news2 = pd.DataFrame(newsapi.get_everything(q="ethereum", language ="en",sort_by='relevancy',page = 2)['articles'])
eth_news3 = pd.DataFrame(newsapi.get_everything(q="ethereum", language ="en",sort_by='relevancy',page = 3)['articles'])
eth_news4 = pd.DataFrame(newsapi.get_everything(q="ethereum", language ="en",sort_by='relevancy',page = 4)['articles'])
eth_news5 = pd.DataFrame(newsapi.get_everything(q="ethereum", language ="en",sort_by='relevancy',page = 5)['articles'])

eth_news = pd.concat([eth_news1,eth_news2,eth_news3,eth_news4,eth_news5])
eth_news.head()

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': 'mashable', 'name': 'Mashable'}",Joseph Green,This blockchain development course bundle is o...,TL;DR: The Cryptocurrency with Ethereum and So...,https://mashable.com/uk/shopping/june-17-crypt...,https://mondrian.mashable.com/2021%252F06%252F...,2021-06-17T04:05:00Z,TL;DR: The Cryptocurrency with Ethereum and So...
1,"{'id': 'mashable', 'name': 'Mashable'}",Tim Marcin,Classic memes that have sold as NFTs,It wasn't long ago that your average person ha...,https://mashable.com/article/classic-memes-sol...,https://mondrian.mashable.com/2021%252F06%252F...,2021-06-20T19:28:07Z,It wasn't long ago that your average person ha...
2,"{'id': 'reuters', 'name': 'Reuters'}",Reuters,Ethereum extends gains to rise 8%; bitcoin fir...,Cryptocurrency Ethereum extended gains to rise...,https://www.reuters.com/technology/ethereum-ri...,https://www.reuters.com/resizer/yeaYVdBQ4_EGCb...,2021-05-31T12:17:00Z,A representation of virtual currency Ethereum ...
3,"{'id': None, 'name': 'Entrepreneur'}",Entrepreneur en Español,Ethereum creator Vitalik Buterin made more tha...,Ethereum billionaire founder Vitalik Buterin b...,https://www.entrepreneur.com/article/374264,https://assets.entrepreneur.com/content/3x2/20...,2021-06-10T19:12:00Z,This article was translated from our Spanish e...
4,"{'id': None, 'name': 'Slashdot.org'}",BeauHD,Norton 360 Antivirus Now Lets You Mine Ethereu...,NortonLifelock has added the ability to mine E...,https://slashdot.org/story/21/06/03/0358213/no...,https://a.fsdn.com/sd/topics/bitcoin_64.png,2021-06-03T10:00:00Z,This new mining feature is called 'Norton Cryp...

In [22]:
# Create the Bitcoin sentiment scores DataFrame
btc_sentiment = []

for content in btc_news['content']:
    sentiment = analyzer.polarity_scores(content)
    compound = sentiment["compound"]
    pos = sentiment["pos"]
    neu = sentiment["neu"]
    neg = sentiment["neg"]
        
    btc_sentiment.append({
            "text": content,
            "compound": compound,
            "positive": pos,
            "negative": neg,
            "neutral": neu   
        })

# Create DataFrame
btc_df = pd.DataFrame(btc_sentiment)

# Reorder DataFrame columns
cols = ["text", "compound", "positive", "negative", "neutral"]
btc_df = btc_df[cols]

btc_df.head()

,text,compound,positive,negative,neutral
0,El Salvador's President Nayib Bukele has made ...,0.8402,0.282,0.0,0.718
1,El Salvador has become the first country in th...,0.1280,0.043,0.0,0.957
2,"It's all about clean energy, it seems. \r\nElo...",0.6908,0.169,0.0,0.831
3,image captionThe move means bitcoin will be ac...,0.2732,0.060,0.0,0.940
4,"Several crypto fans that descended on Miami, F...",0.5574,0.107,0.0,0.893

In [24]:
# Create the Bitcoin sentiment scores DataFrame
eth_sentiment = []

for content in eth_news['content']:
    sentiment = analyzer.polarity_scores(content)
    compound = sentiment["compound"]
    pos = sentiment["pos"]
    neu = sentiment["neu"]
    neg = sentiment["neg"]
        
    eth_sentiment.append({
            "text": content,
            "compound": compound,
            "positive": pos,
            "negative": neg,
            "neutral": neu   
        })

# Create DataFrame
eth_df = pd.DataFrame(eth_sentiment)

# Reorder DataFrame columns
cols = ["text", "compound", "positive", "negative", "neutral"]
eth_df = eth_df[cols]

eth_df.head()

,text,compound,positive,negative,neutral
0,TL;DR: The Cryptocurrency with Ethereum and So...,0.000,0.0,0.000,1.000
1,It wasn't long ago that your average person ha...,-0.296,0.0,0.061,0.939
2,A representation of virtual currency Ethereum ...,0.000,0.0,0.000,1.000
3,This article was translated from our Spanish e...,-0.340,0.0,0.066,0.934
4,This new mining feature is called 'Norton Cryp...,0.000,0.0,0.000,1.000

In [25]:
# Describe the Bitcoin Sentiment
btc_df.describe()

         compound    positive    negative     neutral
count  100.000000  100.000000  100.000000  100.000000
mean     0.059177    0.046790    0.029330    0.923880
std      0.351163    0.063604    0.044144    0.072482
min     -0.778300    0.000000    0.000000    0.718000
25%     -0.081925    0.000000    0.000000    0.871000
50%      0.000000    0.000000    0.000000    0.929000
75%      0.323650    0.083250    0.062250    1.000000
max      0.840200    0.282000    0.178000    1.000000

In [26]:
# Describe the Ethereum Sentiment
eth_df.describe()

         compound    positive    negative     neutral
count  100.000000  100.000000  100.000000  100.000000
mean     0.128436    0.054930    0.024120    0.920970
std      0.347841    0.066266    0.042622    0.076793
min     -0.750600    0.000000    0.000000    0.655000
25%      0.000000    0.000000    0.000000    0.881750
50%      0.000000    0.041000    0.000000    0.927500
75%      0.362175    0.086500    0.057750    1.000000
max      0.848100    0.290000    0.262000    1.000000

### Questions:

Q: Which coin had the highest mean positive score?

*__A: Etheruem had the highest mean positive score, 5.49% vs 4.68% for Bitcoin.__*

Q: Which coin had the highest compound score?

*__A: Ethereum had the highest mean compound score (12.84% vs 5.92% respectively), as well as the highest compound score for an individual article (84.81% vs 84.02% respectively).__*

Q. Which coin had the highest positive score?

*__A: Ethereum had the highest positive score (29% vs 28.2% for ETH)__*

## 2. Natural Language Processing
---
###   Tokenizer

In this section, you will use NLTK and Python to tokenize the text for each coin. Be sure to:
1. Lowercase each word.
2. Remove Punctuation.
3. Remove Stopwords.

In [123]:
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
from string import punctuation
import re

In [124]:
btc_string=" ".join(btc_news['content'].astype(str))

In [152]:
# Create a list of stopwords
sentence = sent_tokenize(btc_string)
words = word_tokenize(btc_string)
sw = set(stopwords.words('english'))
first_result = [word.lower() for word in words if word.lower() not in sw]

# unsure if the list has to be expanded

In [135]:
# Instantiate the lemmatizer
lemmatizer = WordNetLemmatizer()

In [156]:
# Complete the tokenizer function
def tokenizer(text):
    """Tokenizes text."""
    
    # Remove the punctuation from text
    regex = re.compile("[^a-zA-Z ]")
    re_clean = regex.sub('', text)

    # Create a tokenized list of the words
    words = word_tokenize(re_clean)    
    
    # Define the stop words
    sw = stopwords.words('english')
    
    # Lemmatize words into root words
    lem = [lemmatizer.lemmatize(word) for word in words]
   
    # Convert the words to lowercase
    output = [word.lower() for word in lem if word.lower() not in sw]
    
    return output

In [154]:
# Create a new tokens column for Bitcoin
btc_token = btc_news['content'].apply(tokenizer)
btc_df['token'] = btc_token.values
btc_df.head()

,text,compound,positive,negative,neutral,token
0,El Salvador's President Nayib Bukele has made ...,0.8402,0.282,0.0,0.718,"[el, salvadors, president, nayib, bukele, ha, ..."
1,El Salvador has become the first country in th...,0.1280,0.043,0.0,0.957,"[el, salvador, ha, become, first, country, wor..."
2,"It's all about clean energy, it seems. \r\nElo...",0.6908,0.169,0.0,0.831,"[clean, energy, seemselon, musk, tesla, caused..."
3,image captionThe move means bitcoin will be ac...,0.2732,0.060,0.0,0.940,"[image, captionthe, move, mean, bitcoin, accep..."
4,"Several crypto fans that descended on Miami, F...",0.5574,0.107,0.0,0.893,"[several, crypto, fan, descended, miami, flori..."

In [155]:
# Create a new tokens column for Ethereum
eth_token = eth_news['content'].apply(tokenizer)
eth_df['token'] = eth_token.values
eth_df.head()

,text,compound,positive,negative,neutral,token
0,TL;DR: The Cryptocurrency with Ethereum and So...,0.000,0.0,0.000,1.000,"[tldr, cryptocurrency, ethereum, solidity, blo..."
1,It wasn't long ago that your average person ha...,-0.296,0.0,0.061,0.939,"[wasnt, long, ago, average, person, clue, nft,..."
2,A representation of virtual currency Ethereum ...,0.000,0.0,0.000,1.000,"[representation, virtual, currency, ethereum, ..."
3,This article was translated from our Spanish e...,-0.340,0.0,0.066,0.934,"[article, wa, translated, spanish, edition, us..."
4,This new mining feature is called 'Norton Cryp...,0.000,0.0,0.000,1.000,"[new, mining, feature, called, norton, crypto,..."

---

### NGrams and Frequency Analysis

In this section you will look at the ngrams and word frequency for each coin. 

1. Use NLTK to produce the n-grams for N = 2. 
2. List the top 10 words for each coin.

In [159]:
from collections import Counter
from nltk import ngrams

In [169]:
btc_string = " ".join(btc_df['token'].astype(str))

In [165]:
# Generate the Bitcoin N-grams where N=2
btc_counts = Counter(ngrams(btc_string, n=2))
print(dict(btc_counts))

{('[', "'"): 100, ("'", 'e'): 76, ('e', 'l'): 66, ('l', "'"): 103, ("'", ','): 1868, (',', ' '): 1868, (' ', "'"): 1868, ("'", 's'): 188, ('s', 'a'): 61, ('a', 'l'): 120, ('l', 'v'): 29, ('v', 'a'): 38, ('a', 'd'): 67, ('d', 'o'): 67, ('o', 'r'): 110, ('r', 's'): 110, ('s', "'"): 195, ("'", 'p'): 125, ('p', 'r'): 76, ('r', 'e'): 298, ('e', 's'): 153, ('s', 'i'): 57, ('i', 'd'): 50, ('d', 'e'): 59, ('e', 'n'): 200, ('n', 't'): 106, ('t', "'"): 164, ("'", 'n'): 29, ('n', 'a'): 43, ('a', 'y'): 80, ('y', 'i'): 12, ('i', 'b'): 13, ('b', "'"): 11, ("'", 'b'): 203, ('b', 'u'): 17, ('u', 'k'): 7, ('k', 'e'): 45, ('l', 'e'): 64, ('e', "'"): 249, ("'", 'h'): 44, ('h', 'a'): 132, ('a', "'"): 51, ("'", 'm'): 106, ('m', 'a'): 55, ("'", 'g'): 39, ('g', 'o'): 6, ('o', 'o'): 6, ('o', 'd'): 9, ('d', "'"): 197, ('r', 'o'): 56, ('o', 'm'): 30, ('m', 'i'): 41, ('i', 's'): 38, ('s', 'e'): 113, ("'", 'a'): 94, ('o', 'p'): 21, ('p', 't'): 61, ('b', 'i'): 139, ('i', 't'): 162, ('t', 'c'): 123, ('c', 'o'): 203, ('o', 'i'): 127, ('i', 'n'): 294, ('n', "'"): 284, ("'", 'l'): 66, ('e', 'g'): 19, ('g', 'a'): 30, ("'", 't'): 117, ('t', 'e'): 180, ('n', 'd'): 84, ('e', 'r'): 190, ('r', "'"): 222, ("'", 'o'): 25, ('o', 'f'): 7, ('f', 'f'): 25, ('f', 'i'): 42, ('i', 'c'): 50, ('c', 'i'): 28, ('i', 'a'): 17, ('l', 's'): 2, ("'", 'c'): 307, ('c', 'e'): 58, ('t', 'r'): 81, ('r', 'a'): 91, ('a', 'm'): 20, ('m', 'e'): 50, ('r', 'i'): 46, ('c', 'a'): 28, ('a', 'n'): 98, ('o', 'u'): 64, ('u', 'n'): 99, ('r', 'y'): 82, ('y', "'"): 166, ('o', 'n'): 180, ('n', 'g'): 100, ('g', 'r'): 14, ('s', 's'): 35, ("'", 'v'): 15, ('v', 'o'): 1, ('o', 't'): 26, ('e', 'd'): 124, ('a', 'c'): 46, ('c', 'c'): 11, ('e', 'p'): 31, ('c', 'r'): 74, ('y', 'p'): 54, ('t', 'o'): 101, ('o', 'c'): 66, ('c', 'u'): 60, ('u', 'r'): 100, ('r', 'r'): 57, ('n', 'c'): 82, ('c', 'y'): 49, ('a', 'j'): 2, ('j', 'o'): 7, ('i', "'"): 12, ('c', 'h'): 143, ('a', 'r'): 185, ("'", ']'): 100, (']', ' '): 99, (' ', '['): 99, ('b', 'e'): 38, ('e', 'c'): 40, ("'", 'f'): 79, ('i', 'r'): 28, ('s', 't'): 175, ("'", 'w'): 77, ('w', 'o'): 37, ('r', 'l'): 28, ('l', 'd'): 40, ("'", 'r'): 162, ('o', 'g'): 8, ('g', 'n'): 4, ('n', 'i'): 25, ('i', 'z'): 5, ('z', 'e'): 8, ('r', 'd'): 18, ('d', 'i'): 42, ('g', "'"): 87, ('t', 'w'): 18, ('w', 'e'): 48, ('e', 'e'): 57, ('e', 't'): 48, ('d', 'n'): 10, ('n', 'e'): 117, ('s', 'd'): 22, ('d', 'a'): 67, ('t', 'i'): 104, ('n', 's'): 41, ('a', 'b'): 9, ('b', 'l'): 16, ('c', 'l'): 20, ('e', 'a'): 63, ('r', 'g'): 16, ('g', 'y'): 6, ('e', 'm'): 12, ('m', 's'): 4, ('l', 'o'): 76, ('m', 'u'): 15, ('u', 's'): 96, ('s', 'k'): 13, ('k', "'"): 64, ('s', 'l'): 17, ('l', 'a'): 66, ('a', 'u'): 9, ('i', 'p'): 12, ('p', 'p'): 24, ('p', 'l'): 9, ('r', 'k'): 19, ('p', 'a'): 32, ('a', 's'): 47, ('m', 'o'): 40, ('t', 'h'): 54, ('h', "'"): 44, ('n', 'n'): 10, ('n', 'o'): 28, ('b', 'o'): 13, ('u', 'g'): 7, ('g', 'h'): 14, ('h', 't'): 7, ('i', 'l'): 70, ('l', 'l'): 80, ('l', 'i'): 30, ('i', 'o'): 89, ('r', 't'): 21, ("'", 'i'): 48, ('i', 'm'): 17, ('a', 'g'): 18, ('g', 'e'): 53, ('a', 'p'): 24, ('h', 'e'): 43, ('o', 'v'): 14, ('v', 'e'): 51, ('e', 'v'): 27, ('y', 'w'): 2, ('w', 'h'): 7, ('r', 'v'): 7, ('v', 'i'): 43, ('g', 's'): 3, ("'", 'u'): 23, ("'", 'd'): 62, ('o', 'l'): 28, ('l', 'y'): 8, ('i', 'f'): 4, ('f', 'y'): 3, ('o', "'"): 34, ('f', 'a'): 7, ('s', 'c'): 4, ('f', 'l'): 11, ('e', 'k'): 26, ('n', 'f'): 14, ('f', 'e'): 24, ('h', 'i'): 42, ('e', 'y'): 3, ('y', 'v'): 1, ('p', 'o'): 26, ('o', 's'): 55, ('i', 'v'): 21, ('r', 'm'): 8, ('a', 'k'): 31, ('r', 'c'): 10, ('c', 't'): 34, ('f', 'r'): 13, ('i', 'e'): 20, ('l', 'c'): 2, ('b', 'a'): 22, ('c', 'k'): 32, ('e', 'w'): 18, ('w', 'l'): 1, ('w', 'r'): 1, ('t', 'a'): 77, ('k', 'i'): 18, ('s', 'n'): 3, ('m', "'"): 15, ('l', 'k'): 2, ('w', "'"): 28, ('a', 'h'): 5, ('f', "'"): 4, ("'", 'y'): 18, ('y', 'o'): 11, ('c', "'"): 14, ('y', 'a'): 3, ('r', 'u'): 11, ('s', 'o'): 18, ('n', 'b'): 4, ('b', 'b'): 3, ('b', 'c'): 3, ('w', 's'): 4, ('p', 'y'): 1, ('y', 'r'): 1, ('i', 'g'): 33, ('t', 'g'): 1, ('t', 't'): 11, ('t', 'y'): 15, ('s', 'f'): 7, ('f', 'o'): 9, ('u', 'm'): 16, ('m', 'p'): 10, ('p', "'"): 15, ('o', 'x'): 1, ('x', "'"): 4, ('a', 'f'): 19, ('l', 'u'): 38, ('u', 'e'): 15, ("'", 'j'): 48, ('j', 'u'): 55, ('e', 'u'): 83, ('u', 't'): 95, ('e', 'j'): 3, ('j', 'a'): 5, ('d', 'r'): 12, ("'", 'z'): 6, ('a', 'i'): 32, ('a', 't'): 103, ('p', 'u'): 7, ('s', 'h'): 23, ('b', 'r'): 7, ('s', 'm'): 9, ('r', 'w'): 2, ('w', 'a'): 20, ('h', 'u'): 7, ('t', 'u'): 38, ('u', 'a'): 17, ('r', 'b'): 2, ('o', 'a'): 5, ('p', 'i'): 23, ('u', 'v'): 5, ('p', 'h'): 19, ('h', 'o'): 26, ('f', 's'): 1, ('p', 'e'): 42, ('g', 'g'): 15, ('m', 'w'): 3, ('j', 'b'): 2, ('b', 's'): 2, ('s', 'u'): 31, ('u', 'p'): 6, ('t', 's'): 5, ('s', 'p'): 13, ("'", 'q'): 3, ('q', 'u'): 5, ('n', 'y'): 6, ('o', 'e'): 4, ('e', 'q'): 2, ('u', 'i'): 12, ('h', 'c'): 1, ('h', 's'): 1, ('l', 'f'): 2, ('d', 'c'): 2, ('n', 'p'): 2, ('n', 'u'): 8, ('m', 'b'): 8, ('e', 'h'): 1, ('d', 'l'): 3, ('r', 'n'): 8, ('g', 'i'): 10, ('t', 'b'): 1, ('y', 'e'): 9, ('t', 'v'): 1, ('s', 'y'): 3, ('d', 'u'): 10, ('y', 't'): 2, ('o', 'w'): 51, ('w', 'n'): 28, ('d', 'd'): 12, ('e', 'b'): 18, ('t', 'k'): 13, ('k', 'n'): 13, ('d', 'g'): 9, ('n', 'r'): 2, ('g', 'm'): 11, ('m', 't'): 11, ('f', 'j'): 8, ('n', 'j'): 1, ('d', 's'): 6, ('e', 'x'): 21, ('x', 't'): 9, ('k', 'g'): 1, ('d', 'j'): 1, ('o', 'k'): 2, ('k', 'y'): 1, ('k', 'd'): 10, ('x', 'p'): 8, ('t', 'l'): 1, ('n', 'v'): 12, ('t', 'm'): 9, ('e', 'i'): 9, ('e', 'o'): 4, ('u', 'c'): 7, ('n', 'h'): 2, ('a', 'o'): 1, ('b', 'y'): 3, ('y', 's'): 8, ('y', 'm'): 7, ('u', 'b'): 4, ('e', 'f'): 3, ('n', 'q'): 1, ('y', 'b'): 4, ('u', 'l'): 16, ('h', 'w'): 2, ('l', 't'): 9, ('t', 'n'): 1, ('g', 'l'): 4, ('n', 'm'): 2, ('a', 'w'): 7, ('f', 't'): 3, ("'", 'k'): 7, ('h', 'y'): 3, ('x', 'c'): 3, ('m', 'm'): 5, ('g', 'u'): 7, ('f', 'u'): 12, ('u', "'"): 2, ('c', 'b'): 1, ('f', 'n'): 1, ('n', 'k'): 9, ('s', 'w'): 3, ('o', 'j'): 4, ('h', 'n'): 3, ('f', 'd'): 1, ('a', 'q'): 1, ('q', "'"): 2, ('d', 't'): 1, ('k', 's'): 7, ('w', 'i'): 8, ('y', 'j'): 1, ('d', 'b'): 1, ('c', 'n'): 2, ('u', 'y'): 1, ('j', 'e'): 1, ('i', 'x'): 3, ('t', 'f'): 4, ('z', 'o'): 4, ('r', 'f'): 1, ('c', 's'): 3, ('j', 'i'): 1, ('l', 'm'): 4, ('l', 'p'): 1, ('q', 'r'): 1, ('s', 'b'): 1, ('f', 'm'): 1, ('x', 'i'): 2, ('a', 'v'): 1, ('a', 'a'): 1, ('s', 'j'): 3, ('e', 'z'): 3, ('z', 'a'): 3, ('i', 'u'): 3, ('y', 'u'): 1, ('b', 'v'): 1, ('t', 'z'): 2, ('k', 'u'): 1, ('k', 'l'): 1, ('z', 'i'): 1, ('r', 'p'): 4, ('k', 'c'): 3, ('l', 'w'): 1, ('i', 'k'): 1, ('h', 'r'): 1, ('g', 't'): 2, ('o', 'y'): 1, ('n', 'w'): 1, ('y', 'f'): 1, ('b', 't'): 1, ("'", 'x'): 1, ('x', 'm'): 1, ('m', 'r'): 1, ('o', 'b'): 3, ('v', "'"): 1, ('w', 'k'): 4, ('k', 'o'): 2, ('f', 'x'): 1, ('s', 'r'): 1, ('b', 'w'): 1, ('s', 'q'): 2, ('q', 'n'): 1}

In [17]:
# Generate the Ethereum N-grams where N=2
# YOUR CODE HERE!

In [18]:
# Function token_count generates the top 10 words for a given coin
def token_count(tokens, N=3):
    """Returns the top N tokens from the frequency count"""
    return Counter(tokens).most_common(N)

In [19]:
# Use token_count to get the top 10 words for Bitcoin

# print(dict(btc_counts.most_common(10)))

In [20]:
# Use token_count to get the top 10 words for Ethereum

# print(dict(eth_counts.most_common(10)))

---

### Word Clouds

In this section, you will generate word clouds for each coin to summarize the news for each coin

In [21]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import matplotlib as mpl
mpl.rcParams['figure.figsize'] = [20.0, 10.0]

In [22]:
# Generate the Bitcoin word cloud
big_string = ' '.join(btc_df['token'])
btc_text = process_text(big_string)

wc = WordCloud().generate(btc_text)
plt.imshow(wc)

In [23]:
# Generate the Ethereum word cloud
wc = WordCloud().generate(eth_text)
plt.imshow(wc)

---
## 3. Named Entity Recognition

In this section, you will build a named entity recognition model for both Bitcoin and Ethereum, then visualize the tags using SpaCy.

In [24]:
import spacy
from spacy import displacy

In [25]:
# Download the language model for SpaCy
# !python -m spacy download en_core_web_sm

In [26]:
# Load the spaCy model
nlp = spacy.load('en_core_web_sm')

---
### Bitcoin NER

In [27]:
# Concatenate all of the Bitcoin text together
# YOUR CODE HERE!

In [28]:
# Run the NER processor on all of the text
# YOUR CODE HERE!

# Add a title to the document
# YOUR CODE HERE!

In [29]:
# Render the visualization
# YOUR CODE HERE!

In [30]:
# List all Entities
# YOUR CODE HERE!

---

### Ethereum NER

In [31]:
# Concatenate all of the Ethereum text together
# YOUR CODE HERE!

In [32]:
# Run the NER processor on all of the text
# YOUR CODE HERE!

# Add a title to the document
# YOUR CODE HERE!

In [33]:
# Render the visualization
# YOUR CODE HERE!

In [34]:
# List all Entities
# YOUR CODE HERE!

---